jwt:
  key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvcB3P5zyYvb/7EPJEvGS
    RJncziG/tDc2+oiANU8WdOTs1ZxYA+A0YRInCL31AXFfzYG2X4EnsbqPYAZUAatT
    KYyI9+R8ds9JBfk9gKMFRNgOROh/1MYowjrb0VLQAGOaVkEo4ckvHWPpkZj8Ntjy
    qwBPOSK7qv9v5Prd4/kgoAzMiD6nmd4iIco5/UgeqKm7ZpqDIMC0h2sLNnsqupov
    0MPG0/v7T3ljLf77O+2MzGLrvLKwvk1/rEkObG0iVgNMkdpYtcTBvS18x67unmBi
    om02IvQ4/3dRaTqH3PG4p58DdOKczAuYV2IIs2tlguHBirHUiP+QcKsW8y8d2lkS
    cQIDAQAB
    -----END PUBLIC KEY-----
  sign-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9wHc/nPJi9v/s
    Q8kS8ZJEmdzOIb+0Nzb6iIA1TxZ05OzVnFgD4DRhEicIvfUBcV/NgbZfgSexuo9g
    BlQBq1MpjIj35Hx2z0kF+T2AowVE2A5E6H/UxijCOtvRUtAAY5pWQSjhyS8dY+mR
    mPw22PKrAE85Iruq/2/k+t3j+SCgDMyIPqeZ3iIhyjn9SB6oqbtmmoMgwLSHaws2
    eyq6mi/Qw8bT+/tPeWMt/vs77YzMYuu8srC+TX+sSQ5sbSJWA0yR2li1xMG9LXzH
    ru6eYGKibTYi9Dj/d1FpOofc8binnwN04pzMC5hXYgiza2WC4cGKsdSI/5Bwqxbz
    Lx3aWRJxAgMBAAECggEACQ0DIx+jWCEb9/MLxkGLjoYgSBzH/hqcHrsgEmrhUVYS
    DeZVNGofVXn+LqaQ5y63OSA0yL1qXUneyN/EZgf8AYFYjypw3WHpw8Utr9MWzz/W
    /mZwon+JNiqEjal7jmkx1WdqQcrM2oQHghBgB2W1vX5YSQtlFDT2618j8lnRupCM
    g/5Sq1X3qNJL/mCMH3Vbh4knIEMR1FsWxU7C98BEpefKmm8z72JePOksECdfSInv
    4bTb8KkcbInADKU234OP4lItIGoo8NzGKsgLzp5nSbxgl1kXC7twcpRD1ZE3oHLD
    q68lFmrGSwSK/S2G7acBpbRN257EtY0vmDRthaNsGQKBgQD7THaNOcgzFIkKhmCT
    im+qP1ajcZJejHSS52wlyRSOujvmgd25GIyjVKPmYG8OTEgqFUXmQPiWZGBNhp6J
    JzfeWVyiuQ0MTRPuFAWg0H/pxR8X3xa6852M5oUWF5e943cx8wMMJYV7QNh6hVin
    mL6sj2OYk19X+WtbsqLQ8d7zLwKBgQDBTTz+O1hZnOZhXU8uFhR6jzbhXr7J/S46
    sTSq+2ls01eEat2yMnpK9rjaHORAmJKdUoW3M7R5cVVL68OAEEtl4Ig9EERKkI2Z
    OHnB4Ao+30xKLsNBDMstAWwIog0QvbxdLnBKQfg3JbN8Bb08bQI3z2odLHGDnj0u
    R+qqGQtsXwKBgEYlw/oMJRxNISv08sR8oksNvyuEqm0GHAxd2Ux64ugsiEgB/FiM
    x8VX/SBzzsxY8tP8eDSb8khY4KEDcQGsFuZUX410xnWmlmeg4ylOykYBJnrNZVTu
    aA5K0t+l2k/BTSZ+RV2Ao9AR+9vHmUW/V4pnxE904+p0z0kbhmN5ANk1AoGAFW2b
    gk9P1vdGrqpqWaCG+qMfoVIgckHHuyfjv8SJBlBTVlGGa/eeiOrayQsE3ohLUHdS
    bWGk8wV2QClNjcfAo/WFBMfl2iI2IDMbhDtyx093pI2UhYSGjWGn+TkFm8J8vBOm
    zQSNIIfkYq48MROgeFFc4QkJOF71R0kfoWWPV58CgYBrFiMOUvgL0m6dk/W2eY1N
    BHmP8ewezNbsOM87jyetdCzRbmd50ubI5w0tnBWnqcLRp5yagx8C+oqMQtbyyygj
    5B4h/t6JHmc6snLWAI9FeZOzs+gj/qj3W1QaUHEYXmPQDqIIuPWQ1QCyWbM+nSsL
    cjG5y/XLHnQnhPm+rUOWgA==
    -----END PRIVATE KEY-----
  refresh-key: "9fc3887ed7f588adbc6d175b849aedb5a61e34c98bb7a62a6d2fd5233031aca0"